Vinoteca-MVC-Core/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Vinoteca_MVC_Core.Data;
using Vinoteca_MVC_Core.DataLayer.Repository.Interfaces;
using Vinoteca_MVC_Core.Models.Models;
using Vinoteca_MVC_Core.ViewModels.Product;

namespace Vinoteca_MVC_Core.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {     
            return View();
        }
        public IActionResult Offers()
        {
            var productList = _unitOfWork.Products.GetAll(); // Acá tiene que devolver en realidad ofertas...
            return View(productList);
        }
        [HttpGet]
        public IActionResult UpSert(int? id)
        {
            var productVm = new ProductEditVm
            {
                Product = new Product(),
                WineriesList = _unitOfWork.Wineries
                     .GetAll()
                     .Select(c => new SelectListItem
                     {
                         Text = c.WineryName,
                         Value = c.Id.ToString()
                     }),
                VarietiesList = _unitOfWork.Varieties
                     .GetAll()
                     .Select(c => new SelectListItem
                     {
                         Text = c.VarietyName,
                         Value = c.Id.ToString()
                     }),

            };

            if (id == null || id == 0)
            {
                return View(productVm);

            }
            else
            {
                var wwwRootPath = _webHostEnvironment.WebRootPath;
                productVm.Product = _unitOfWork.Products.Get(p => p.Id == id.Value);
                if (productVm.Product.ImageUrl != null)
                {
                    string oldImage = Path.Combine(wwwRootPath, productVm.Product.ImageUrl.TrimStart('\\'));
                    if (!System.IO.File.Exists(oldImage))
                    {
                        var noExiste = @"\images\SinImagenDisponible.jpg";
                        productVm.Product.ImageUrl = noExiste;
                    }
                }
                return View(productVm);

            }
        }

        [HttpPost]
        public IActionResult UpSert(ProductEditVm productVm, IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                productVm.WineriesList = _unitOfWork.Wineries
                     .GetAll()
                     .Select(c => new SelectListItem
                     {
                         Text = c.WineryName,
                         Value = c.Id.ToString()
                     });
                productVm.VarietiesList = _unitOfWork.Varieties
                     .GetAll()
                     .Select(c => new SelectListItem
                     {
                         Text = c.VarietyName,
                         Value = c.Id.ToString()
                     });

                return View(productVm);
            }
            if (file != null)
            {
                var wwwRootPath = _webHostEnvironment.WebRootPath;
                var fileName = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(file.FileName);

                if (productVm.Product.ImageUrl != null)
                {
                    var oldImage = Path.Combine(wwwRootPath, productVm.Product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImage))
                    {
                        System.IO.File.Delete(oldImage);
                    }
                }

                var uploadFolder = Path.Combine(wwwRootPath, @"images\products\");
                using (var fileStream = new FileStream(Path.Combine(
                    uploadFolder, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                productVm.Product.ImageUrl = @"\images\products\" + fileName + extension;
            }
            if (productVm.Product.Id == 0)
            {
                _unitOfWork.Products.Add(productVm.Product);
            }
            else
            {
                _unitOfWork.Products.Update(productVm.Product);
            }
            _unitOfWork.Save();
            return RedirectToAction("Index");

        }
        #region API CALL 
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Products.GetAll();
            List<ProductListVm> productsListVm = new List<ProductListVm>();
            foreach (var product in productList)
            {
                var productVm = new ProductListVm
                {
                    Id = product.Id,
                    Description = product.Description,
                    Stock = product.Stock,
                    Winery = _unitOfWork.Wineries.Get(w => w.Id == product.WineryId).WineryName,
                    Variety = _unitOfWork.Varieties.Get(v => v.Id == product.VarietyId).VarietyName,
                    Price = product.Price,
                };
                productsListVm.Add(productVm);
            };
            return Json(new { data = productsListVm });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return Json(new { success = false, message = "Not Found" });
            }
            var productDelete = _unitOfWork.Products.Get(p => p.Id == id);
            if (productDelete == null)
            {
                return Json(new { success = false, message = "Product Not Found" });
            }
            try
            {
                _unitOfWork.Products.Delete(productDelete);
                _unitOfWork.Save();
                var wwwRothPath = _webHostEnvironment.ContentRootPath;
                if (productDelete.ImageUrl != null)
                {
                    var imageToDelete = Path.Combine(wwwRothPath, productDelete.ImageUrl);
                    if (System.IO.File.Exists(imageToDelete))
                    {
                        System.IO.File.Delete(imageToDelete);
                    }
                }
                return Json(new { success = true, message = "Product removed succesfully" });

            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
        #endregion
    }
}

Vinoteca-MVC-Core/Controllers/VarietyController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Vinoteca_MVC_Core.Data;
using Vinoteca_MVC_Core.DataLayer.Repository.Interfaces;
using Vinoteca_MVC_Core.Models.Models;

namespace Vinoteca_MVC_Core.Controllers
{
    public class VarietyController : Controller
    {
        private readonly IUnitOfWork  _unitOfWork;

        public VarietyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
		{
			var varietyList = _unitOfWork.Varieties.GetAll();
			return View(varietyList);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Variety variety)
		{
			if (!ModelState.IsValid)
			{
				return View(variety); 
			}
			if (_unitOfWork.Varieties.Exists(variety))
			{
				ModelState.AddModelError(string.Empty, "Variety already exists. Try another different.");
				return View(variety);
			}
            _unitOfWork.Varieties.Add(variety);
            _unitOfWork.Varieties.Save();
            TempData["success"]="Record added successfully";
			return RedirectToAction("Index");	
		}
        [HttpGet]
        public IActionResult Edit(int? id)
        {
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var variety = _unitOfWork.Varieties.Get(v=> v.Id == id);
			if (variety == null)
			{
				return NotFound();
			}

            return View(variety);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Variety variety)
        {
            if (!ModelState.IsValid)
            {
                return View(variety);
            }
            if (_unitOfWork.Varieties.Exists(variety))
            {
                ModelState.AddModelError(string.Empty, "Variety already exists. Try another different.");
                return View(variety);
            }
            _unitOfWork.Varieties.Update(variety);
            _unitOfWork.Varieties.Save();
            TempData["success"] = "Record updated successfully";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var variety = _unitOfWork.Varieties.Get(v => v.Id == id);
            if (variety == null)
            {
                return NotFound();
            }

            return View(variety);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var variety = _unitOfWork.Varieties.Get(v => v.Id == id);
            if (variety == null)
            {
                ModelState.AddModelError(string.Empty, "Variety does not exist.");
            }
            _unitOfWork.Varieties.Delete(variety);
            _unitOfWork.Varieties.Save();
            TempData["success"] = "Record removed successfully";

            return RedirectToAction("Index");
        }
    }
}

Vinoteca-MVC-Core/Controllers/WineryController.cs
using Microsoft.AspNetCore.Mvc;
using Vinoteca_MVC_Core.Data;
using Vinoteca_MVC_Core.DataLayer.Repository.Interfaces;
using Vinoteca_MVC_Core.Models.Models;

namespace Vinoteca_MVC_Core.Controllers
{
    public class WineryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public WineryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var wineryList = _unitOfWork.Wineries.GetAll();
            return View(wineryList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Winery winery)
        {
            if (!ModelState.IsValid)
            {
                return View(winery);
            }
            if (_unitOfWork.Wineries.Exists(winery))
            {
                ModelState.AddModelError(string.Empty, "Winery already exists. Try another different.");
                return View(winery);
            }
            _unitOfWork.Wineries.Add(winery);
            _unitOfWork.Wineries.Save();
            TempData["success"] = "Record added successfully";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var winery = _unitOfWork.Wineries.Get(v => v.Id == id);
            if (winery == null)
            {
                return NotFound();
            }

            return View(winery);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Winery winery)
        {
            if (!ModelState.IsValid)
            {
                return View(winery);
            }
            if (_unitOfWork.Wineries.Exists(winery))
            {
                ModelState.AddModelError(string.Empty, "Winery already exists. Try another different.");
                return View(winery);
            }
            _unitOfWork.Wineries.Update(winery);
            _unitOfWork.Wineries.Save();
            TempData["success"] = "Record updated successfully";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var winery = _unitOfWork.Wineries.Get(v => v.Id == id);
            if (winery == null)
            {
                return NotFound();
            }

            return View(winery);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var winery = _unitOfWork.Wineries.Get(v => v.Id == id);
            if (winery == null)
            {
                ModelState.AddModelError(string.Empty, "Winery does not exist.");
            }
            _unitOfWork.Wineries.Delete(winery);
            _unitOfWork.Wineries.Save();
            TempData["success"] = "Record removed successfully";

            return RedirectToAction("Index");
        }
    }
}

Vinoteca-MVC-Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vinoteca_MVC_Core</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/Vinoteca_MVC_Core.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="@Url.Content(Vinoteca_MVC_Core.Utilities.WC.LogoIcon)" class="d-block w-100" alt="..." width="60" height="60">
                    <div>
                        RAMON
                    </div>
                    <div>
                        WINES
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Variety" asp-action="Index">Varieties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Winery" asp-action="Index">Wineries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Offers"><b>¡OFFERS!</b></a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Vinoteca_MVC_Core - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Vinoteca-MVC-Core/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}